const INDIA_REGIONS = [
  { name: 'Andhra Pradesh', code: 'AP', region_type: 'State' },
  { name: 'Arunachal Pradesh', code: 'AR', region_type: 'State' },
  { name: 'Assam', code: 'AS', region_type: 'State' },
  { name: 'Bihar', code: 'BR', region_type: 'State' },
  { name: 'Chhattisgarh', code: 'CG', region_type: 'State' },
  { name: 'Goa', code: 'GA', region_type: 'State' },
  { name: 'Gujarat', code: 'GJ', region_type: 'State' },
  { name: 'Haryana', code: 'HR', region_type: 'State' },
  { name: 'Himachal Pradesh', code: 'HP', region_type: 'State' },
  { name: 'Jharkhand', code: 'JH', region_type: 'State' },
  { name: 'Karnataka', code: 'KA', region_type: 'State' },
  { name: 'Kerala', code: 'KL', region_type: 'State' },
  { name: 'Madhya Pradesh', code: 'MP', region_type: 'State' },
  { name: 'Maharashtra', code: 'MH', region_type: 'State' },
  { name: 'Manipur', code: 'MN', region_type: 'State' },
  { name: 'Meghalaya', code: 'ML', region_type: 'State' },
  { name: 'Mizoram', code: 'MZ', region_type: 'State' },
  { name: 'Nagaland', code: 'NL', region_type: 'State' },
  { name: 'Odisha', code: 'OD', region_type: 'State' },
  { name: 'Punjab', code: 'PB', region_type: 'State' },
  { name: 'Rajasthan', code: 'RJ', region_type: 'State' },
  { name: 'Sikkim', code: 'SK', region_type: 'State' },
  { name: 'Tamil Nadu', code: 'TN', region_type: 'State' },
  { name: 'Telangana', code: 'TS', region_type: 'State' },
  { name: 'Tripura', code: 'TR', region_type: 'State' },
  { name: 'Uttar Pradesh', code: 'UP', region_type: 'State' },
  { name: 'Uttarakhand', code: 'UK', region_type: 'State' },
  { name: 'West Bengal', code: 'WB', region_type: 'State' },
  { name: 'Andaman and Nicobar Islands', code: 'AN', region_type: 'Union Territory' },
  { name: 'Chandigarh', code: 'CH', region_type: 'Union Territory' },
  { name: 'Dadra and Nagar Haveli and Daman and Diu', code: 'DN', region_type: 'Union Territory' },
  { name: 'Delhi', code: 'DL', region_type: 'Union Territory' },
  { name: 'Jammu and Kashmir', code: 'JK', region_type: 'Union Territory' },
  { name: 'Ladakh', code: 'LA', region_type: 'Union Territory' },
  { name: 'Lakshadweep', code: 'LD', region_type: 'Union Territory' },
  { name: 'Puducherry', code: 'PY', region_type: 'Union Territory' },
];

module.exports = {
  INDIA_REGIONS,
};
